In [5]:
import numpy as np
my_arr = np.arange(100000000)


In [6]:
my_list = list(range(100000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 752 ms, sys: 1.64 s, total: 2.39 s
Wall time: 2.39 s


In [11]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 32.7 s, sys: 8.78 s, total: 41.5 s
Wall time: 41.6 s


In [14]:
data = np.random.randn(2,3)
data

array([[ 1.50538622, -0.31407865,  1.99727372],
       [-0.32501397,  0.09243161,  0.50321267]])

In [16]:
data * 10

array([[15.05386216, -3.14078654, 19.97273716],
       [-3.25013967,  0.92431606,  5.03212675]])

In [18]:
data + data

array([[ 3.01077243, -0.62815731,  3.99454743],
       [-0.65002793,  0.18486321,  1.00642535]])

In [20]:
data.shape

(2, 3)

In [22]:
data.dtype

dtype('float64')

In [25]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1.dtype

dtype('float64')

In [32]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2.ndim
arr2.shape
arr2.dtype

dtype('int64')

In [36]:
np.zeros(10)
np.zeros((3,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [43]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [46]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [51]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)
numeric_float = numeric_strings.astype(float)
numeric_float.dtype

dtype('float64')